k9s:
  cluster: barmer-waaspreprod-oidc
  namespace:
    active: verimi-system
    lockFavorites: false
    favorites:
      - verimi-system
      - verimi-osc-waaspreprod1
      - default
  view:
    active: namespace
  featureGates:
    nodeShell: false
  proxy: null
