k9s:
  cluster: default
  namespace:
    active: dev4
    lockFavorites: false
    favorites:
      - dev7
      - dev1
      - dev4
      - default
  view:
    active: d2
  featureGates:
    nodeShell: false
  proxy: null
