k9s:
  cluster: default
  namespace:
    active: waas-dev6
    lockFavorites: false
    favorites:
      - waas-dev5
      - waas-dev2
      - waas-dev6
      - waas-dev4
      - ingress
      - galactus
      - waas-int
      - waas-dev3
      - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
